# Generated by Django 3.2.18 on 2023-03-09 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clgmnt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clgmnt_app.course')),
            ],
        ),
    ]
